version: 2
updates:
- package-ecosystem: pip
  directory: "/src"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.59
    - 1.16.63
    - 1.17.12
    - 1.17.17
    - 1.17.22
    - 1.17.27
    - 1.17.3
    - 1.17.33
    - 1.17.39
    - 1.17.44
    - 1.17.49
    - 1.17.53
    - 1.17.7
  - dependency-name: faker
    versions:
    - 5.6.5
    - 5.8.0
    - 6.1.1
    - 6.4.1
    - 6.5.0
    - 6.6.0
    - 6.6.2
    - 6.6.3
    - 7.0.1
    - 8.0.0
    - 8.1.0
  - dependency-name: peewee
    versions:
    - 3.14.0
    - 3.14.1
    - 3.14.2
    - 3.14.3
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: sentry-sdk
    versions:
    - 0.19.5
    - 0.20.1
    - 0.20.3
  - dependency-name: python-telegram-bot
    versions:
    - "13.1"
    - "13.2"
    - "13.3"
  - dependency-name: openpyxl
    versions:
    - 3.0.6
  - dependency-name: pytest
    versions:
    - 6.2.1
    - 6.2.2
  - dependency-name: mongoengine
    versions:
    - 0.22.1
  - dependency-name: flake8-broken-line
    versions:
    - 0.3.0
