version: '3.6'

services:
  web:
    build: ./src
    restart: always
    command: uwsgi --http :8000 --module srv.web:app --workers 1 --threads 1
    volumes:
      - ./src:/srv:delegated
      #- ../seller-stats/seller_stats:/usr/local/lib/python3.8/site-packages/seller-stats:delegated
      #- ../seller-stats:/seller-stats:delegated
    env_file:
      - ./.env
      - ./.env.docker
    links:
      - mongo
    ports:
      - 80:8000
    depends_on:
      - worker
      - mongo
      - postgres

  worker:
    build: ./src
    restart: always
    command: celery -A srv.tasks:celery worker
    volumes:
      - ./src:/srv:delegated
      #- ../seller-stats/seller_stats:/usr/local/lib/python3.8/site-packages/seller-stats:delegated
      #- ../seller-stats:/seller-stats:delegated
    environment:
      - C_FORCE_ROOT=on
    env_file:
      - ./.env
      - ./.env.docker
    links:
      - redis
      - mongo
    depends_on:
      - mongo
      - redis
      - postgres

  flower:
    build: ./src
    restart: always
    command: celery -A srv.tasks:celery flower --port=5555
    volumes:
      - ./src:/srv:delegated
    links:
      - redis
    env_file:
      - ./.env
      - ./.env.docker
    ports:
      - 5555:5555

  redis:
    image: redis:4-alpine

  mongo:
    image: mongo:4.2.2-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wildsearch_mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=wildsearch_mongo_password
      - MONGO_INITDB_DATABASE=wildsearch_mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - ./infra/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  postgres:
    image: postgres
    env_file:
      - ./.env
      - ./.env.docker
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432

  # Зачем в этой схеме нужен Nginx я пока не решил
  #nginx:
  #  image: nginx:1.13-alpine
  #  volumes:
  #    - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #  depends_on:
  #    - hook_catcher
  #  ports:
  #    - 80:80

volumes:
  mongo: {}
  database-data: # named volumes can be managed easier using docker-compose